# Generated by Django 5.1.4 on 2024-12-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects')),
                ('name', models.CharField(max_length=225)),
                ('date_time', models.DateTimeField()),
                ('place', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'db_table': 'project',
                'ordering': ['-id'],
            },
        ),
    ]
