# Generated by Django 5.1.4 on 2024-12-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('short_description', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=225)),
                ('Participant', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
                'db_table': 'form',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='booking_project'),
        ),
    ]
