# Generated by Django 5.1.4 on 2024-12-10 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_form_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.project'),
            preserve_default=False,
        ),
    ]
