# Generated by Django 5.1.4 on 2024-12-10 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_form_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='project',
        ),
        migrations.AddField(
            model_name='form',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.event'),
            preserve_default=False,
        ),
    ]
