# Generated by Django 5.1.4 on 2024-12-11 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_form_project_form_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='event',
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.event'),
        ),
    ]
