# Generated by Django 5.1.4 on 2024-12-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_form_event_alter_form_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
